# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_image',
            field=models.ImageField(blank=True, default='post_img/profile.png', null=True, upload_to='post_img/'),
        ),
    ]
